### PR TITLE
Update DNNVisionGPU Env in azureml-assets

### PR DESCRIPTION
**Pull request by shubhamiit**
Updating DNN Vision env in azureml-assets to include the latest changes.

### CODE REVIEW

**Review by rjaincc — APPROVED** [review]

**Comment by rjaincc** [comment]
@shubhamiit - Let's please update component versions as well in the same PR.

**Comment by yiyoulin** [comment]
do we have a successful run associated with this? the reason why I'm asking is that, simply upgrading the torch will break our code in yolo. so in my PR: https://msdata.visualstudio.com/Vienna/_git/AzureMlCli/pullrequest/1145455 I have some edits in utils.py. 

would love to know if in this PR it's also needed, if not, why. :) thanks!

**Comment by PhaniShekhar** [comment]
> do we have a successful run associated with this? the reason why I'm asking is that, simply upgrading the torch will break our code in yolo. so in my PR: https://msdata.visualstudio.com/Vienna/_git/AzureMlCli/pullrequest/1145455 I have some edits in utils.py.
> 
> would love to know if in this PR it's also needed, if not, why. :) thanks!

Agree with Yiyou's comments. If we have edits in package (dnn-vision or other packages), they have to be released to pypi before we can release this environment.
When we release this environment, it picks up the latest pypi azureml packages. If some required changes (like Yiyou mentioned) are not present in the current pypi version, it could break scenarios.

**Review by PhaniShekhar — CHANGES_REQUESTED** [review]
Please wait for azureml package release.

**Comment by shubhamiit** [comment]
Abandoning this PR as it will not work current pypi package as per team's comment

**Pull request closed without merging**
