### PR TITLE
Pin Werkzeug==2.2.3 to fix the vulnerability issue

### PR DESCRIPTION
**Pull request by vinuthakaranth**
Fix "VulnerabilityName": Python (Pip) Security Update for Werkzeug (GHSA-xg9f-g7g7-2323),
in responsibleai images

pinning Werkzeug to 2.2.3 fixes this issue.

### CODE REVIEW

**Review by tongyu-microsoft — DISMISSED** [review]

**Review by imatiach-msft — DISMISSED** [review]

**Comment by imatiach-msft** [comment]
it looks like there was some error in build envs:

  ERROR: Cannot install -r /condaenv.wjrb58u9.requirements.txt (line 14) and markupsafe<=2.0.1 because these package versions have conflicting dependencies.

**Comment by vinuthakaranth** [comment]
> it looks like there was some error in build envs:
> 
> ERROR: Cannot install -r /condaenv.wjrb58u9.requirements.txt (line 14) and markupsafe<=2.0.1 because these package versions have conflicting dependencies.

yeah, updating in responsibleai repo might fix this issue

**Review by gaugup — COMMENTED** [review]
can you pin these in conda_dependencies.yml?

**Comment by vinuthakaranth** [comment]
> can you pin these in conda_dependencies.yml?

I tried in the previous commit. It resulted in dependency issues. So trying if this approach so we don't install markupsafe and Werkzeug together. Happy to try other ways to avoid dependency issues.

**Comment by vinuthakaranth** [comment]
> it looks like there was some error in build envs:
> 
> ERROR: Cannot install -r /condaenv.wjrb58u9.requirements.txt (line 14) and markupsafe<=2.0.1 because these package versions have conflicting dependencies.

trying updating in docker file to check if it helps.

**Review by gaugup — COMMENTED** [review]
did you confirm from the build log that Werkzeug is actually installed at 2.2.3 in the images?

**Review by imatiach-msft — APPROVED** [review]

**Comment by vinuthakaranth** [comment]
> did you confirm from the build log that Werkzeug is actually installed at 2.2.3 in the images?

yes, Werkzeug 2.2.3 is installed.
image

**Review by gaugup — APPROVED** [review]

**Pull request merged**
