### PR TITLE
Vision model release to prod

### PR DESCRIPTION
**Pull request by gauravrajguru**
This PR is for releasing Vision tasks models (total 11) to azureml registry. 
The model cards will look like this - 
[microsoft-beit-base-patch16-224-pt22k-ft22k: 7 - Azure AI | Machine Learning Studio](https://ml.azure.com/registries/azureml-dev/models/microsoft-beit-base-patch16-224-pt22k-ft22k/version/7?tid=72f988bf-86f1-41af-91ab-2d7cd011db47&reloadCount=1#overview)

[google-vit-base-patch16-224](https://ml.azure.com/registries/azureml-dev/models/google-vit-base-patch16-224/version/7?tid=72f988bf-86f1-41af-91ab-2d7cd011db47#overview)

[facebook-deit-base-patch16-224](https://ml.azure.com/registries/azureml-dev/models/facebook-deit-base-patch16-224/version/7?tid=72f988bf-86f1-41af-91ab-2d7cd011db47#overview)

[microsoft-swinv2-base-patch4-window12-192-22k](https://ml.azure.com/registries/azureml-dev/models/microsoft-swinv2-base-patch4-window12-192-22k/version/7?tid=72f988bf-86f1-41af-91ab-2d7cd011db47#overview)

[mask_rcnn_swin-t-p4-w7_fpn_1x_coco: 5 - Azure AI | Machine Learning Studio](https://ml.azure.com/registries/azureml-dev/models/mask_rcnn_swin-t-p4-w7_fpn_1x_coco/version/5?tid=72f988bf-86f1-41af-91ab-2d7cd011db47&reloadCount=1#overview)

[yolof_r50_c5_8x8_1x_coco: 5 - Azure AI | Machine Learning Studio](https://ml.azure.com/registries/azureml-dev/models/yolof_r50_c5_8x8_1x_coco/version/5?tid=72f988bf-86f1-41af-91ab-2d7cd011db47&reloadCount=1#overview)

[vfnet_r50_fpn_mdconv_c3-c5_mstrain_2x_coco](https://ml.azure.com/registries/azureml-dev/models/vfnet_r50_fpn_mdconv_c3-c5_mstrain_2x_coco/version/5?tid=72f988bf-86f1-41af-91ab-2d7cd011db47#overview)
[sparse_rcnn_r101_fpn_300_proposals_crop_mstrain_480-800_3x_coco](https://ml.azure.com/registries/azureml-dev/models/sparse_rcnn_r101_fpn_300_proposals_crop_mstrain_480-800_3x_coco/version/5?tid=72f988bf-86f1-41af-91ab-2d7cd011db47#overview)

[deformable_detr_twostage_refine_r50_16x2_50e_coco](https://ml.azure.com/registries/azureml-dev/models/deformable_detr_twostage_refine_r50_16x2_50e_coco/version/5?tid=72f988bf-86f1-41af-91ab-2d7cd011db47#overview)

[vfnet_x101_64x4d_fpn_mdconv_c3-c5_mstrain_2x_coco](https://ml.azure.com/registries/azureml-dev/models/vfnet_x101_64x4d_fpn_mdconv_c3-c5_mstrain_2x_coco/version/5?tid=72f988bf-86f1-41af-91ab-2d7cd011db47#overview)

[sparse_rcnn_r50_fpn_300_proposals_crop_mstrain_480-800_3x_coco](https://ml.azure.com/registries/azureml-dev/models/sparse_rcnn_r50_fpn_300_proposals_crop_mstrain_480-800_3x_coco/version/5?tid=72f988bf-86f1-41af-91ab-2d7cd011db47#overview)

(Except heading of inference image changed from "Model Result Visualization" to "Model inference - visualization for a sample image")

### CODE REVIEW

**Review by raduk — APPROVED** [review]

**Review by rjaincc — APPROVED** [review]

**Comment by praveenmathamsetty** [comment]
⁠

Gaurav: Could you share the successful deployments log/studio link of these models and inference results in the PR?

**Comment by praveenmathamsetty** [comment]
FTed model inferencing test results?

**Comment by praveenmathamsetty** [comment]
The input format is different from other standard foundational models is this closed by our PMs?

**Comment by praveenmathamsetty** [comment]
Playground experience will be provided to the end users?

**Comment by gauravrajguru** [comment]
> Playground experience will be provided to the end users?

No, it's not supported as of now. @RSavage2 working on it to bring up this experience. Hence, we added result visualization images in model card.

**Review by RSavage2 — APPROVED** [review]

**Review by praveenmathamsetty — APPROVED** [review]

**Pull request merged**
