### PR TITLE
add deepspeed examples

### PR DESCRIPTION
**Pull request by cassieesvelt**
Adds examples for deepspeed training and autotuning.

### CODE REVIEW

**Review by savitamittal1 — COMMENTED** [review]
Can you create data folder in a single place and reuse in both trainign job as well as autotune

**Review by savitamittal1 — COMMENTED** [review]
In the README for autotune, do you want to provide detail on where optimal config will be generated and downloaded so it can be used in training.

**Comment by cassieesvelt** [comment]
> @cassieesvelt please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="{Microsoft}"]

**Comment by cassieesvelt** [comment]
> @cassieesvelt please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="Microsoft"

**Comment by vizhur** [comment]
What is the support and validation story for these samples? You probably want some tests to run on the samples

**Comment by cassieesvelt** [comment]
> What is the support and validation story for these samples? You probably want some tests to run on the samples

We want to get these samples in right now, we are planning to add testing with the CE migration.

**Review by savitamittal1 — APPROVED** [review]

**Pull request merged**
