### PR TITLE
Updated oai ft pipeline component to 0.0.8

### PR DESCRIPTION
**Pull request by vvatsalya**

### CODE REVIEW

**Review by daholste — APPROVED** [review]

**Review by skasturi — APPROVED** [review]

**Comment by skasturi** [comment]
Please check failed tests.

**Review by skasturi — CHANGES_REQUESTED** [review]
Please check failed tests.

**Comment by vvatsalya** [comment]
I see in https://github.com/Azure/azureml-assets/actions/runs/6256833564/job/16988263992?pr=1280 `check-execution-context / Check execution context`, may be we need to add this tag ?
image

**Review by ganik — APPROVED** [review]

**Comment by skasturi** [comment]
> I see in https://github.com/Azure/azureml-assets/actions/runs/6256833564/job/16988263992?pr=1280 `check-execution-context / Check execution context`, may be we need to add this tag ? Do we need to avoid the forking of repo ? image


@vvatsalya Yes. We prefer creating branches in the same repository.

**Review by skasturi — APPROVED** [review]

**Pull request merged**
