### PR TITLE
Roberta base openai detector batch success hftransformers

### PR DESCRIPTION
**Pull request by KonakanchiSwathi**
Roberta base openai detector batch success hftransformers

### CODE REVIEW

**Comment by KonakanchiSwathi** [comment]
Job Link: -https://ml.azure.com/experiments/id/6789dc75-aadc-48b1-bcdd-4b4f69acc0dd/runs/jovial_tree_r1hrkvry6q?wsid=/subscriptions/72c03bf3-4e69-41af-9532-dfcdc3eefef4/resourceGroups/shared-finetuning-rg/providers/Microsoft.MachineLearningServices/workspaces/v-swathikon&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#

**Comment by skasturi** [comment]
Could you please cheque why the end point profiler failed?

**Comment by skasturi** [comment]
Please update the description to reflect all the changes being done in this pull request

**Review by skasturi — CHANGES_REQUESTED** [review]
Please address review comments

**Comment by KonakanchiSwathi** [comment]
added new pr so closing this

**Pull request closed without merging**
