### PR TITLE
updating classification models version

### PR DESCRIPTION
**Pull request by shubhamiit**
Need to lower down the batch size a bit to accomodate Single Node SIngle GPU DS ORT runs

New BS:
1. Diet: 180 https://ml.azure.com/experiments/id/2b2befc0-d9ea-4b1b-ac09-80cf5bb31c7d/runs/4717caed-f3c6-4ae1-a5c2-ec8ca2e890e2?wsid=/subscriptions/dbd697c3-ef40-488f-83e6-5ad4dfb78f9b/resourceGroups/rupaljain-rs/providers/Microsoft.MachineLearningServices/workspaces/rupaljain-workspace&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#
2. VIT: 180 https://ml.azure.com/experiments/id/2b2befc0-d9ea-4b1b-ac09-80cf5bb31c7d/runs/57eb9b07-dc22-4622-9cef-be4506048d73?wsid=/subscriptions/dbd697c3-ef40-488f-83e6-5ad4dfb78f9b/resourceGroups/rupaljain-rs/providers/Microsoft.MachineLearningServices/workspaces/rupaljain-workspace&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#
3. Swinv2: 90https://ml.azure.com/experiments/id/2b2befc0-d9ea-4b1b-ac09-80cf5bb31c7d/runs/cf18d110-d398-43cf-8d63-09cae310dbc4?wsid=/subscriptions/dbd697c3-ef40-488f-83e6-5ad4dfb78f9b/resourceGroups/rupaljain-rs/providers/Microsoft.MachineLearningServices/workspaces/rupaljain-workspace&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#
4. beit: 150 https://ml.azure.com/experiments/id/2b2befc0-d9ea-4b1b-ac09-80cf5bb31c7d/runs/647c9dfd-cd83-40b4-9529-fadf0e0571ca?wsid=/subscriptions/dbd697c3-ef40-488f-83e6-5ad4dfb78f9b/resourceGroups/rupaljain-rs/providers/Microsoft.MachineLearningServices/workspaces/rupaljain-workspace&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#

### CODE REVIEW

**Comment by rjaincc** [comment]
@shubhamiit - Please run for all models / datasets combinations. Let's ensure we don't see any regression.

**Review by rjaincc — APPROVED** [review]
Please merge after verifying on all models and datasets combinations.

**Review by MadhuM02 — APPROVED** [review]
nit: models are not getting downloaded from our registries in the sample runs provided. might be  running with task level defaults.

**Comment by shubhamiit** [comment]
> e not getting downloaded from our registries in the sample runs provided. might be running with task level defaults.

Yep, Testing with new defaults providing by UI

**Comment by shubhamiit** [comment]
> Please merge after verifying on all models and datasets combinations.

Please find the experiment link for testing: https://ml.azure.com/experiments/id/2b2befc0-d9ea-4b1b-ac09-80cf5bb31c7d?wsid=/subscriptions/dbd697c3-ef40-488f-83e6-5ad4dfb78f9b/resourceGroups/rupaljain-rs/providers/Microsoft.MachineLearningServices/workspaces/rupaljain-workspace&tid=72f988bf-86f1-41af-91ab-2d7cd011db47

**Pull request merged**
