### PR TITLE
Update conda_dependencies.yaml

### PR DESCRIPTION
**Pull request by kicha0**
Add torch and tensorflow dependencies.

### CODE REVIEW

**Comment by romanlutz** [comment]
What's motivating this? Installing all of these is likely going to cause issues later on.

**Comment by kicha0** [comment]
this enables support of tensorflow and pytorch model cpu inference. I agree adding model dependencies to rai image is not a sustainable approach, so the next steps to supporting all model types would likely be done by online endpoint

**Review by vizhur — CHANGES_REQUESTED** [review]
remove wheels installed from a blob. also remove all pip freeze stuff and any other unnecessary instructions.

as a side note, please consider to update scipy that has a vulnerability approaching due date

**Comment by imatiach-msft** [comment]
closing old PRs

**Pull request closed without merging**
